# Generated by Django 4.2.2 on 2023-07-12 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='artist_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Painting_name', models.CharField(max_length=100)),
                ('mediam', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('artcode', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image_url', models.ImageField(upload_to='pics/')),
                ('art_available', models.BooleanField()),
                ('i_am_not_robot', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
