# Generated by Django 4.2.2 on 2023-07-12 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallary', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_gallary.cart')),
                ('painting_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_gallary.artist_sell')),
            ],
        ),
    ]
