# Generated by Django 4.2.2 on 2023-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallary', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='artworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.CharField(max_length=200)),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('team3', models.CharField(max_length=200)),
                ('team4', models.CharField(max_length=200)),
                ('team5', models.CharField(max_length=200)),
                ('team6', models.CharField(max_length=200)),
                ('team7', models.CharField(max_length=200)),
                ('team8', models.CharField(max_length=200)),
            ],
        ),
    ]
