# Generated by Django 4.2.2 on 2023-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallary', '0007_artworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='compitition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('feedback', models.TextField()),
                ('image_url', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
